/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateObject */

#ifndef _Included_CreateObject
#define _Included_CreateObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CreateObject
 * Method:    outputDate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateObject_outputDate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
